title: DSC180A Methodology 4    
description: "Course project site for DSC180A Methodology 4"
url: "https://dtsukamoto.github.io/DSC180A-Methodology-4/" 
baseurl: "/DSC180A-Methodology-4"  
theme: minima

