# _config.yml
title: DSC180A Methodology 4     # Your site title
description: "Course project site for DSC180A Methodology 4"
url: "https://dtsukamoto.github.io/DSC180A-Methodology-4/"  # Your GitHub Pages URL
baseurl: "/DSC180A-Methodology-4"    # Repository name for project pages
theme: minima
author:
  name: David Tsukamoto
  email: dtsukamoto@ucsd.edu

# Optional settings
markdown: kramdown
